# Remote OM power_manager default config

default_mode=normal
allow_suspend=false
normal_heartbeat_interval=5
low_power_heartbeat_interval=60
wakeup_source=rtc,key
state_path=/var/run/power_manager.mode
log_path=/var/log/power_manager/power_manager.log

